# Regenerates SKILLS.md by scanning every skill root on this machine.
# Run after installing, removing, or writing a skill.  No arguments.

$ErrorActionPreference = 'Stop'
$kit = Split-Path $PSScriptRoot -Parent

# Where skills live. Add a row here if a new root appears.
$roots = @(
    @{ Group = 'Own (versioned in this repo)'; Path = "$kit\skills";                              Depth = 2 }
    @{ Group = 'DVMind official';              Path = "$env:USERPROFILE\.dvmind\skills\official"; Depth = 2 }
    @{ Group = 'DVMind local';                 Path = "$env:USERPROFILE\.dvmind\skills\local";    Depth = 2 }
    @{ Group = 'Plugins';                      Path = "$env:USERPROFILE\.claude\plugins\cache";   Depth = 6 }
)

function Get-SkillMeta($file) {
    $lines = Get-Content -LiteralPath $file.FullName -Encoding UTF8
    $name = $null; $desc = $null; $trigger = $null

    if ($lines.Count -gt 0 -and $lines[0].TrimStart([char]0xFEFF) -eq '---') {
        $end = 1
        while ($end -lt $lines.Count -and $lines[$end] -ne '---') { $end++ }
        for ($i = 1; $i -lt $end; $i++) {
            if ($lines[$i] -match '^name:\s*(.+?)\s*$')    { $name = $Matches[1].Trim('"',"'") }
            if ($lines[$i] -match '^trigger:\s*(.+?)\s*$') { $trigger = $Matches[1].Trim('"',"'") }
            if ($lines[$i] -match '^description:\s*(.*)$') {
                $desc = $Matches[1].Trim()
                # folded scalars (>- or |) and empty values continue on indented lines
                if ($desc -eq '' -or $desc -match '^[>|]') {
                    $desc = ''
                    for ($j = $i + 1; $j -lt $end -and $lines[$j] -match '^\s+\S'; $j++) {
                        $desc += ' ' + $lines[$j].Trim()
                    }
                }
                $desc = $desc.Trim().Trim('"',"'")
            }
        }
    }

    # Frontmatter-less skills (DVMind style): fall back to folder name and first prose line.
    if (-not $name) { $name = $file.Directory.Name }
    if (-not $desc) {
        $desc = ($lines | Where-Object { $_ -notmatch '^\s*(#|<!--|-{3,}|\s*$)' } | Select-Object -First 1)
    }
    if (-not $desc) { $desc = '(no description)' }

    # One line, no pipes, so the markdown table survives.
    $desc = ($desc -replace '\s+', ' ') -replace '\|', '/'
    if ($desc.Length -gt 200) { $desc = $desc.Substring(0, 197) + '...' }

    [pscustomobject]@{ Name = $name; Trigger = $trigger; Description = $desc; Path = $file.FullName }
}

$out = [System.Collections.Generic.List[string]]::new()
$out.Add('# Skill Index')
$out.Add('')
$out.Add('Generated by `tools/index-skills.ps1`. Do not edit by hand; rerun the script.')
$out.Add('')
$out.Add('Names are what you invoke. Paths are where the instructions live -- read the')
$out.Add('SKILL.md directly if the current tool cannot invoke skills natively.')
$out.Add('')

$total = 0
foreach ($root in $roots) {
    if (-not (Test-Path $root.Path)) { continue }

    $files = Get-ChildItem -LiteralPath $root.Path -Recurse -Depth $root.Depth -Filter 'SKILL.md' -File -ErrorAction SilentlyContinue
    # Plugin cache keeps one dir per installed version; keep only the newest of each name.
    $skills = $files | ForEach-Object { Get-SkillMeta $_ } |
              Sort-Object Name, @{ Expression = { (Get-Item $_.Path).LastWriteTime }; Descending = $true } |
              Group-Object Name | ForEach-Object { $_.Group[0] } | Sort-Object Name
    if (-not $skills) { continue }

    $out.Add("## $($root.Group)")
    $out.Add('')
    $out.Add('| Skill | What it does | Path |')
    $out.Add('|---|---|---|')
    foreach ($s in $skills) {
        $rel = $s.Path.Replace($env:USERPROFILE, '~').Replace("$kit\", '')
        # Frontmatter name and the thing you actually type are not always the same.
        $label = if ($s.Trigger -and $s.Trigger -notmatch [regex]::Escape($s.Name)) {
                     "``$($s.Name)`` (``$($s.Trigger)``)"
                 } else { "``$($s.Name)``" }
        $out.Add("| $label | $($s.Description) | ``$rel`` |")
        $total++
    }
    $out.Add('')
}

# Health check: slash commands and index files that point at a SKILL.md which is gone.
# This rot is silent -- the command exists, the agent reads nothing, and improvises.
$dangling = @()
$refSources = @(
    "$env:USERPROFILE\.claude\commands\*.md"
    "$env:USERPROFILE\.dvmind\skills\*\index.md"
)
foreach ($pattern in $refSources) {
    foreach ($f in (Get-ChildItem -Path $pattern -File -ErrorAction SilentlyContinue)) {
        foreach ($m in [regex]::Matches((Get-Content -LiteralPath $f.FullName -Raw), '[A-Za-z]:\\[^\s`''"]+?SKILL\.md')) {
            if (-not (Test-Path -LiteralPath $m.Value)) {
                $dangling += [pscustomobject]@{ From = $f.Name; Missing = $m.Value }
            }
        }
    }
}

if ($dangling) {
    $out.Add('## BROKEN references')
    $out.Add('')
    $out.Add('These point at a SKILL.md that does not exist. Invoking them makes an agent')
    $out.Add('read nothing and improvise. Fix or delete the referring file.')
    $out.Add('')
    $out.Add('| Referenced from | Missing file |')
    $out.Add('|---|---|')
    foreach ($d in ($dangling | Sort-Object Missing -Unique)) {
        $out.Add("| ``$($d.From)`` | ``$($d.Missing.Replace($env:USERPROFILE, '~'))`` |")
    }
    $out.Add('')
}

$out.Add('---')
$out.Add("$total skills indexed. $(($dangling | Sort-Object Missing -Unique).Count) broken references.")

# ASCII-safe, no BOM: the global CLAUDE.md already got mangled by BOM + UTF-16 once.
[System.IO.File]::WriteAllLines("$kit\SKILLS.md", $out, (New-Object System.Text.UTF8Encoding($false)))
Write-Host "SKILLS.md written: $total skills."
